image: atomfrede/gitlab-ci-jhipster-stack
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules
    - .gradle/wrapper
    - .gradle/caches
    - .maven

services:
    - docker:dind

stages:
  - build
  - test
  - package
  - release
  - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export MAVEN_USER_HOME=`pwd`/.maven
    - npm install

maven-build:
    stage: build
    script:
        - ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME

gulp-build:
    stage: build
    script:
        - gulp build
        
maven-test:
    stage: test
    script:
        - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/surefire-reports/*
            
test_sonar_job:
  stage: test
  script:
    - cd /builds/jCOTINEAU/sonarqubeIntegrationTest
    - ls
    - sleep 60
    - sonar-scanner -X -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.url=https://gitlab.com -Dsonar.gitlab.user_token=QjX7KV6DQ5E8s5vmbz84 -Dsonar.project.name=$CI_PROJECT_NAME 
  tags:
    - docker


gulp-test:
    stage: test
    script:
        - gulp test

#protractor-test:
#    stage: test
#    script:
#        - gulp protractor

gatling-test:
    stage: test
    allow_failure: true
    script:
        - ./mvnw gatling:execute -Dmaven.repo.local=$MAVEN_USER_HOME
    before_script:
        - npm install
        - export MAVEN_USER_HOME=`pwd`/.maven
        - ./mvnw spring-boot:run -Dmaven.repo.local=$MAVEN_USER_HOME &
    artifacts:
        paths:
            - target/gatling/*

maven-repackage:
    stage: package
    script:
        - ./mvnw package -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/*.war



    
docker-build:
    image: docker:latest
    stage: release
    dependencies:
        - maven-repackage
    before_script:
        - docker info
        - cp target/*.war src/main/docker
    script:
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" registry.gitlab.com
        - docker build -f src/main/docker/Dockerfile -t registry.gitlab.com/amit-an/ci-example-maven src/main/docker
        - docker push registry.gitlab.com/amit-an/ci-example-maven
